export const strings = {
  app: {
    title: "Cookmark",
  },
  search: {
    placeholder: "Search recipes...",
    noResults: "No recipes found",
    noResultsHint: "Try adjusting your search or filters.",
    clearSearchAndFilters: "Clear search and filters",
    resultsCount: (count: number) => `${count} recipe${count === 1 ? "" : "s"} found`,
  },
  filters: {
    difficulty: "Difficulty",
    time: "Time",
    tags: "Tags",
    protein: "Protein",
    diet: "Diet",
    type: "Type",
    easy: "Easy",
    medium: "Medium",
    hard: "Hard",
    under30: "Under 30 min",
    under60: "Under 1 hour",
    over60: "1+ hours",
  },
  sort: {
    label: "Sort by",
    activeLabel: (sort: string) => `Sort: ${sort}`,
    dateDesc: "Date (newest first)",
    dateAsc: "Date (oldest first)",
    nameAsc: "Name (A-Z)",
    nameDesc: "Name (Z-A)",
    timeAsc: "Time (shortest first)",
    timeDesc: "Time (longest first)",
    difficultyEasy: "Difficulty (easy first)",
    difficultyHard: "Difficulty (hard first)",
    shortDateDesc: "Newest",
    shortDateAsc: "Oldest",
    shortNameAsc: "Name A-Z",
    shortNameDesc: "Name Z-A",
    shortTimeAsc: "Shortest",
    shortTimeDesc: "Longest",
    shortDifficultyEasy: "Easiest",
    shortDifficultyHard: "Hardest",
  },
  recipe: {
    prep: "Prep:",
    cook: "Cook:",
    total: "Total:",
    servings: "Servings:",
    cuisine: "Cuisine:",
    ingredients: "Ingredients",
    instructions: "Instructions",
    viewSource: "View Recipe Source",
    difficultyLabel: "Difficulty",
    notFound: "Recipe not found",
    backToList: "Back to recipes",
  },
  tags: {
    chicken: "Chicken",
    pork: "Pork",
    beef: "Beef",
    fish: "Fish",
    vegan: "Vegan",
    dessert: "Dessert",
    lactoseFree: "Lactose-free",
    lowSugar: "Low-Sugar",
    cake: "Cake",
    vegetarian: "Vegetarian",
    eggs: "Eggs",
    mealPrep: "Meal-prep",
  },
  filterDrawer: {
    title: "Filters",
    clearAll: "Clear all",
    filtersButton: "Filters",
  },
  favorites: {
    sectionTitle: "Favourites",
    only: "Favourites only",
    add: (name: string) => `Add ${name} to favourites`,
    remove: (name: string) => `Remove ${name} from favourites`,
  },
  recipeList: {
    name: "Recipe Name",
    difficulty: "Difficulty",
    time: "Time",
  },
  pagination: {
    previous: "Previous",
    next: "Next",
    goToPage: (page: number) => `Go to page ${page}`,
    pageInfo: (current: number, total: number) => `Page ${current} of ${total}`,
  },
} as const;
